server:
  port: 8089
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.31.14:8083/eureka/,http://192.168.31.14:8084/eureka/
spring:
  application:
    name: turbine
turbine:
  aggregator:
    cluster-config: default
  appConfig: app1
  clusterNameExpression: new String("default")
