eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.31.14:8083/eureka/,http://192.168.31.14:8084/eureka/
spring:
  application:
    name: app1
management:
  endpoint:
    hystrix:
      stream:
        enabled: true
    health:
      enabled: true
    auditevents:
      enabled: true
