server:
  port: 8083
#  ssl:
#  #    key-store: classpath:214446451490908.pfx
#  #    key-store-password: 214446451490908
#    key-store: classpath:214463323110575.pfx
#    key-store-password: 214463323110575
#    key-store-type: PKCS12


eureka:
  instance:
    hostname: eureka1
    prefer-ip-address: true
#    statusPageUrl: https://${eureka.hostname}/info
#    healthCheckUrl: https://${eureka.hostname}/health
#    homePageUrl: https://${eureka.hostname}/
  client:
#    registerWithEureka: false
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka2:8084/eureka/




