server:
  port: 8085

eureka:
  instance:
    hostname: eureka3
    prefer-ip-address: true
#    statusPageUrl: https://${eureka.hostname}/info
#    healthCheckUrl: https://${eureka.hostname}/health
#    homePageUrl: https://${eureka.hostname}/
  client:
#    registerWithEureka: false
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://192.168.31.14:8083/eureka/,http://192.168.31.14:8084/eureka/

